twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['_form/material_theme.html.twig']
    globals:
        system_logo: 'static/img/logo-adinvest-302px.png'